version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: sunday
      time: '15:00'
      timezone: America/Mexico_City
    open-pull-requests-limit: 3

    groups:
      all-npm-dependencies:
        patterns:
          - '*'
        update-types:
          - patch
          - minor

    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: sunday
      time: '15:00'
      timezone: America/Mexico_City
    open-pull-requests-limit: 2

    groups:
      github-actions:
        patterns:
          - '*'

    commit-message:
      prefix: chore
      include: scope
